from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aac743e58085'
down_revision = 'd2ccb6b7847d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=140), nullable=True))
        batch_op.create_index(batch_op.f('ix_post_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_slug'))
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
