from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2ccb6b7847d'
down_revision = 'eaf26325caa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=120), nullable=True))

    # ### end Alembic commands ###
